#!/bin/bash

# Run Prettier on files
npx prettier --write "*/{public,src,test}/**/*.{js,jsx,ts,tsx,html,css,json}"

# Add the changes to the staging area
git add -u .

# Continue with the commit
exit 0