name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: yarn install

      - name: Build backend project
        run: yarn build-backend

      - name: Build frontend project
        run: yarn build-frontend

      - name: Archive frontend production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build

      - name: Archive backend production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-build
          path: backend/build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: yarn install


      - name: Run tests
        run: yarn test-backend
